# Generated by Django 3.1.7 on 2021-09-07 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0002_configuracionproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateField(blank=True, null=True)),
                ('user_updated_id', models.IntegerField(blank=True, null=True)),
                ('rubro', models.IntegerField()),
                ('sucursal', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('timbrado', models.IntegerField()),
                ('fecha_inicio_timbrado', models.DateField()),
                ('fecha_fin_timbrado', models.DateField()),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Configuracion de Venta',
            },
        ),
    ]
