# Generated by Django 3.1.7 on 2021-09-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='sub_total_sin_iva',
            field=models.IntegerField(default=0),
        ),
    ]
