# Generated by Django 3.1.7 on 2021-09-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cuotaventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
