# Generated by Django 3.1.7 on 2021-10-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_anulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_cheque',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
