# Generated by Django 2.2.12 on 2021-07-10 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('user_updated_id', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('metraje', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('disenho', models.CharField(choices=[('estampado', 'Estampado'), ('liso', 'Liso')], default='Estampado', max_length=20)),
                ('categoria', models.CharField(choices=[('manteleria', 'Mantelería'), ('pantaloneria', 'Pantalonería'), ('camiseria', 'Camisería')], default='Mantelería', max_length=20)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
