# Generated by Django 3.1.7 on 2021-08-21 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateField(blank=True, null=True)),
                ('user_updated_id', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(error_messages={'unique': 'El campo Codigo ya existe'}, max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('metraje', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('precio_compra', models.IntegerField()),
                ('precio_compra_anterior', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipos.categoria')),
                ('disenho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipos.disenho')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
