# Generated by Django 3.1.7 on 2021-08-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0002_tela_fecha_eliminacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tela',
            old_name='precio',
            new_name='precio_compra',
        ),
        migrations.AddField(
            model_name='tela',
            name='precio_venta',
            field=models.FloatField(default=0),
        ),
    ]
