# Generated by Django 3.1.7 on 2021-08-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0003_auto_20210816_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tela',
            name='codigo',
            field=models.CharField(error_messages={'unique': 'El campo Ruc ya existe'}, max_length=200, unique=True),
        ),
    ]
