# Generated by Django 3.1.7 on 2021-07-08 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('user_updated_id', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('razon_social', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('ruc', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('tipo_cliente', models.CharField(choices=[('persona_fisica', 'Persona Física'), ('persona_juridica', 'Persona Juridica')], default='persona_fisica', max_length=20)),
                ('nro_telefono', models.CharField(max_length=20)),
                ('nro_celular', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicaciones.ciudad')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
