# Generated by Django 3.1.7 on 2021-07-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20210716_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nro_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
