# Generated by Django 2.2.12 on 2021-07-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20210716_0101'),
        ('clientes', '0002_cliente_fecha_eliminacion'),
    ]

    operations = [
    ]
