# Generated by Django 3.1.7 on 2021-07-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20210716_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre_cliente']},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
    ]
