# Generated by Django 2.2.12 on 2021-07-20 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_merge_20210719_2130'),
        ('clientes', '0004_auto_20210719_2159'),
    ]

    operations = [
    ]
