# Generated by Django 3.1.7 on 2021-08-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20210810_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
