# Generated by Django 3.1.7 on 2021-08-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20210816_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, error_messages={'unique': 'El campo Cedula/Ruc ya existe'}, max_length=50, null=True, unique=True),
        ),
    ]
