# Generated by Django 3.1.7 on 2021-09-24 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0002_banco_cobro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cajas.banco'),
        ),
    ]
