# Generated by Django 2.2.12 on 2021-10-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0002_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='monto_cheque',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_cierre',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_efectivo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_egreso',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_ingreso',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
