# Generated by Django 3.1.7 on 2021-09-30 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_anulado'),
        ('cajas', '0003_auto_20210923_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='cuota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.cuotaventa'),
        ),
    ]
