# Generated by Django 3.1.7 on 2021-09-30 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0004_auto_20210929_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cajas.banco'),
        ),
    ]
