# Generated by Django 2.2.12 on 2021-10-07 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0003_auto_20211001_2241'),
        ('cajas', '0005_auto_20210929_2350'),
    ]

    operations = [
    ]
