# Generated by Django 3.1.7 on 2021-10-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0006_merge_20211006_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='numero_cheque',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
