# Generated by Django 3.1.7 on 2021-10-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0007_cobro_numero_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='monto_actual',
            field=models.IntegerField(null=True),
        ),
    ]
