# Generated by Django 3.1.7 on 2021-10-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0008_caja_monto_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='monto_actual',
            field=models.IntegerField(null=True),
        ),
    ]
