# Generated by Django 3.1.7 on 2021-10-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0010_auto_20211015_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='numero_comprobante',
            field=models.CharField(blank=True, error_messages={'unique': 'Número de Comprobante ya existente'}, max_length=20, null=True, unique=True),
        ),
    ]
