# Generated by Django 3.1.7 on 2021-10-21 19:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_cuotacompra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cajas', '0011_auto_20211020_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateField(blank=True, null=True)),
                ('user_updated_id', models.IntegerField(blank=True, null=True)),
                ('monto_pagado', models.IntegerField(default=0)),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque')], default='efectivo', max_length=20)),
                ('numero_cheque', models.IntegerField(default=0, null=True)),
                ('fecha_pago', models.DateField(default=datetime.datetime.now)),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cajas.banco')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajas.caja')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
                ('cuota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.cuotacompra')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pago',
            },
        ),
    ]
