# Generated by Django 3.1.7 on 2021-12-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinventario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
