# Generated by Django 2.2.12 on 2021-07-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='fecha_eliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='fecha_eliminacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
