# Generated by Django 2.2.12 on 2021-07-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='fecha_eliminacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
