# Generated by Django 2.2.12 on 2021-08-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_fecha_eliminacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nro_celular',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
