# Generated by Django 2.2.12 on 2021-08-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20210811_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_empresa',
            field=models.CharField(max_length=100),
        ),
    ]
