# Generated by Django 2.2.12 on 2021-08-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_auto_20210811_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(max_length=100),
        ),
    ]
