# Generated by Django 3.1.7 on 2021-08-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_auto_20210811_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
