# Generated by Django 2.2.12 on 2021-08-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_auto_20210815_2331'),
        ('proveedores', '0006_auto_20210816_2302'),
    ]

    operations = [
    ]
