# Generated by Django 3.1.7 on 2021-08-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_merge_20210817_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(error_messages={'unique': 'El campo Ruc ya existe'}, max_length=100, unique=True),
        ),
    ]
